alphagov/notifications-ruby-client

- lib/notifications/client/speaker.rb
- spec/notifications/client/get_notification_spec.rb
- spec/notifications/client/get_notifications_spec.rb
- spec/notifications/client/request_errors_spec.rb
- spec/support/stub_post_request.rb
Changed `Net::HTTP.new` to `Net::HTTP.start` to use 
inbuild https vertification and setup
Without this change the API attempts to connect via HTTP regards of API URLs protocol and returns: 
```Errno::ECONNRESET: Connection reset by peer``` 
when trying to send emails.
> Connect to API via https

- .travis.yml
- notifications-ruby-client.gemspec
Trying to run the tests for this repo on Travis gives the following error:
```
Bundler could not find compatible versions for gem "bundler":
In Gemfile:
bundler (~> 1.11) ruby
Current Bundler version:
bundler (1.7.9)
```
This seems to be because we’re using quite an old version of the `bundler` Gem.
Also updates Travis config to use a newer Ruby for the same reason.
> Update Bundler version to run tests on Travis

- lib/notifications/client.rb
- lib/notifications/client/notification.rb
- lib/notifications/client/speaker.rb
- spec/factories/client_notifications.rb
- spec/factories/client_notifications_collections.rb
- spec/notifications/client/get_notifications_spec.rb
Fixes for:
* get_notification -> update hash nesting in response JSON
* get_notifications -> incorrect URL - remove trailing slash
* field list -> remove old field - content_char_count
Update
* field list -> add new fields
This has been tested again the live system for the pensionwise account.
> Update notifications response object

- .gitignore
- .idea/vcs.xml
- README.md
- bin/test_client.rb
- lib/notifications/client.rb
- lib/notifications/client/notification.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/version.rb
- Added a bin/test_client.rb in order to do end to end testing.  …
- Updated the notifications object to default to nil if the attribute is missing.
The sms notification response does not include the subject, but email does.
The end-to-end tests should fail if an attribute is missing.
- Set the version to 1.0.0, as we plan to deploy this version to rubygems
- allow the post data for send_email/send_sms to be a Hash or a String
- Update README.md
- Finish bin/test_client.rb hopefully this is maintainable and readable now.
> Prepare for deployment

- lib/notifications/client.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/version.rb
- spec/factories/notifications_client.rb
- spec/notifications/client_spec.rb
In research we’ve seen people mix up the service ID and API key because they’re both 36 character UUIDs. We can’t get rid of the service ID because it’s used to look up the API key.
Instead, we should change API key to be one long string, which contains both the service ID, API key and (optionally) the name of the key. For example:
**API key**
`casework_production-8b3aa916-ec82-434e-b0c5-d5d9b371d6a3-dcdc5083-2fee-4fba-8afd-51f3f4bcb7b0`
This commit changes the client to make the `secret` argument optional. If it’s not passed, they we attempt to extract it from the second argument (service ID) instead.
If a new-style API key is passed with a service ID as well then we just strip out the parts of the key that aren’t the secret.
> Make secret include API key + service ID

- lib/notifications/client.rb
- lib/notifications/client/version.rb
There's no need to pull in a (large) external library to do something that's provided by the standard library.
Also, the dependency on Active Support wasn't actually specified in the gemspec, so use failed with sandboxed bundles...
> Replace AR delegation with stdlib Forwardable

- Makefile
- docker/Dockerfile
- docker/Makefile
- lib/notifications/client/speaker.rb
- lib/notifications/client/version.rb
The HTTP.start is pretty lame, because it is overriding the HTTP.new's p_addr parameter's value with nil, which turns off the http proxy explicitely. BAAAAH.
As I needed to do a small code change, please review.
> Use http proxy for Docker

- CHANGELOG.md
- README.md
- bin/test_client.rb
- lib/notifications/client.rb
- lib/notifications/client/notification.rb
- lib/notifications/client/notifications_collection.rb
- lib/notifications/client/request_error.rb
- lib/notifications/client/response_notification.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/version.rb
- notifications-ruby-client.gemspec
- spec/factories/client_notifications.rb
- spec/factories/client_notifications_collections.rb
- spec/factories/client_request_errors.rb
- spec/factories/notifications_client.rb
- spec/notifications/client/email_notification_spec.rb
- spec/notifications/client/get_notification_spec.rb
- spec/notifications/client/get_notifications_spec.rb
- spec/notifications/client/request_errors_spec.rb
- spec/notifications/client/sms_notification_spec.rb
- spec/notifications/client/speaker_spec.rb
- spec/notifications/client_spec.rb
- spec/support/stub_post_request.rb
Upgrade to use version 2 of the notification APIs
- change to ResponseNotificationm response to .
- change to Notification, response to getNotificaitonById()
- change to NotificationList, response to getNotifications()
- New filters for getNotifications(status, notificationType, reference, olderThanId)
- Update the README to reflect all these changes.
Now at version 2.0.0
> Upgrade to API version 2

- bin/test_client.rb
For the migration of paas we changed how the api calls persist the notification, so we need to wait for it to be there.
> Update integration tests. 

- CHANGELOG.md
- README.md
- bin/test_client.rb
- lib/notifications/client.rb
- lib/notifications/client/response_template.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/template_collection.rb
- lib/notifications/client/template_preview.rb
- lib/notifications/client/version.rb
- spec/factories/template_list.rb
- spec/factories/template_preview.rb
- spec/factories/template_response.rb
- spec/notifications/client/generate_template_preview_spec.rb
- spec/notifications/client/get_all_templates_spec.rb
- spec/notifications/client/get_template_spec.rb
- spec/notifications/client/get_template_version_spec.rb
* Added methods to get templates and generate a preview of a template.
* `get_template_by_id` - get the latest version of a template by id.
* `get_template_version` - get the template by id and version.
* `get_all_templates` - get all templates, can be filtered by template type.
* `generate_template_preview` - get the contents of a template with the placeholders replaced with the given personalisation.
> Add template methods

- .github/PULL_REQUEST_TEMPLATE.md
- lib/notifications/client/version.rb
We should clarify what our expectations are of external developers contributing to our codebase.
A good way to do this is through a pull request template, which lets developers check off what they’ve done. A lot of the GOV.UK frontend repos do this, eg
https://github.com/alphagov/govuk_elements/blob/3c5c43a6fd4209cf2b6d180e7a5eadf6fa94c132/.github/PULL_REQUEST_TEMPLATE.md
This commit also documents how we do version numbering, so that an external developer would have a reasonable chance of being able to increment the version number in the right way.
> Add a pull request template

- lib/notifications/client/version.rb
- notifications-ruby-client.gemspec
Hello :wave: from across the office. I'm on the GOV.UK Email team.
We've hit a problem installing versions of this gem beyond 2.2.0 as we hit dependency conflicts. The version of JWT that is required for this gem seems to be quite new (released in October) and this gem doesn't make use of any of the newer features. 
This change in dependency rules will still mean that in situations where you don't have another dependency that uses JWT you'll still have the latest version, however it won't forbid building for an application that has dependencies on earlier version of JWT.
> Loosen dependency on JWT

- CHANGELOG.md
- lib/notifications/client.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/uuid_validator.rb
- lib/notifications/client/version.rb
- spec/factories/notifications_client.rb
- spec/notifications/client/uuid_validator_spec.rb
- spec/notifications/client_spec.rb
We were receiving some difficult to understand errors inside the `jwt` gem caused by setting the API key to something invalid. This change makes it check the UUIDs derived from the API key are valid on initialisation of the client and provides a helpful error message if they are invalid.
- ~[ ] I’ve update the documentation (in `README.md`)~ (probably not applicable?)
> Validate UUIDs derived from the API key

- README.md
Some links in the table of contents weren't working and some content was
appearing nested inside other sections, instead of in its own section.
> Remove spare details and summary tags to fix layout

- spec/notifications/client/email_notification_spec.rb
- spec/notifications/client/generate_template_preview_spec.rb
- spec/notifications/client/get_all_templates_spec.rb
- spec/notifications/client/get_notification_spec.rb
- spec/notifications/client/get_notifications_spec.rb
- spec/notifications/client/get_template_spec.rb
- spec/notifications/client/get_template_version_spec.rb
- spec/notifications/client/letter_notification_spec.rb
- spec/notifications/client/sms_notification_spec.rb
Updated the unit tests to test that the methods are hitting the correct endpoints in notifications-api. This makes the tests for the ruby client more consistent with tests for the other clients.
[Pivotal story](https://www.pivotaltracker.com/story/show/153281515)
> Test that methods hit the correct endpoint of notifications-api

- README.md
I assumed the most recent 250 messages would span across a wider time
period but regardless of the numbers, only the last 7 days worth of
responses are returned.
Corrects some misleading API documentation.
> Clarify API responses

- CHANGELOG.md
- README.md
- bin/test_client.rb
- lib/notifications/client/notification.rb
- lib/notifications/client/version.rb
- notifications-ruby-client.gemspec
- spec/factories/client_notifications.rb
- spec/notifications/client/get_notification_spec.rb
The `Notification` class now has an additional property, `created_by_name`. This affects the return value of the `.get_notification` method.
Also updated the minor versions of some development dependencies and bumped the gem version from 2.6.0 to 2.7.0.
> Add created_by_name to Notification response and bump version

- DOCUMENTATION.md
Update 'reply-to address' label to match Settings
A previous pull request updated the _Email reply-to address_ field in Notify settings to include a '-'. This change brings the guidance in line with the service content.
> Update 'reply-to address' label to match Settings

- CHANGELOG.md
- DOCUMENTATION.md
- bin/test_client.rb
- lib/notifications/client/response_template.rb
- lib/notifications/client/version.rb
- spec/factories/template_response.rb
- spec/notifications/client/get_template_spec.rb
- spec/notifications/client/get_template_version_spec.rb
The `Template` class now has a `name` property, which is the name of the template as set in Notify.
This change affects the response from these two methods:
* `get_template_by_id`
* `get_template_version`
[Pivotal story](https://www.pivotaltracker.com/story/show/160020331)
>  Return 'name' when fetching a template

- CHANGELOG.md
- DOCUMENTATION.md
- bin/test_client.rb
- lib/notifications/client.rb
- lib/notifications/client/helper_methods.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/uuid_validator.rb
- lib/notifications/client/version.rb
- spec/notifications/client/helper_methods_spec.rb
- spec/notifications/client/precompiled_letter_spec.rb
- spec/notifications/client/request_errors_spec.rb
* Added a helper method, `prepare_upload`, to allow users to send a document with an email
* Added error handling for server errors - we were only catching client errors before.
* Updated the documentation to include precompiled letters and sending documents by email and bumped the version.
> Add document download helper method and bump version

- CHANGELOG.md
- DOCUMENTATION.md
- lib/notifications/client/request_error.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/version.rb
- spec/notifications/client/request_errors_spec.rb
This PR adds various subclasses of `RequestError` based on the status code of the response.
| Class | Code |
| --- | --- |
| `ClientError` | 400-499 |
| `BadRequestError` | 400 |
| `AuthError` | 403 |
| `NotFoundError` | 404 |
| `RateLimitError` | 429 |
| `ServerError` | 500-599 |
The idea here is that it makes it easier for clients to handle errors differently by catching the various exception classes rather than having to look at the code. In the future this could be expanded to understand the difference between a `BadRequestError` and a `ValidationError` both having the same code of 400, but I think this is a nice improvement for now.
[Trello Card](https://github.com/alphagov/notifications-ruby-client/pull/63)
> Error subclasses based on code

- DOCUMENTATION.md
Minor fix for the tables. We'll still have to think about how to display tables with 4 columns at some point, since the tech docs template will render them like this:
> Fix documentation tables format

- CHANGELOG.md
- DOCUMENTATION.md
- bin/test_client.rb
- lib/notifications/client.rb
- lib/notifications/client/notification.rb
- lib/notifications/client/response_notification.rb
- lib/notifications/client/response_precompiled_letter.rb
- lib/notifications/client/speaker.rb
- lib/notifications/client/version.rb
- spec/factories/client_notifications.rb
- spec/notifications/client/precompiled_letter_spec.rb
Allow users to set postage when sending precompiled letters.
> Set postage when sending precompiled letters and add it to response schema

- CHANGELOG.md
- DOCUMENTATION.md
- bin/test_client.rb
- lib/notifications/client/template_preview.rb
- lib/notifications/client/version.rb
- spec/factories/template_preview.rb
- spec/notifications/client/generate_template_preview_spec.rb
Adds support for a new field that the API is returning.
> Add `html` field to template preview response

- Makefile
- bin/generate_docker_env.sh
- docker/Dockerfile
- docker/Makefile
This reverts commit 68c5fc27a7ad007fe8101c1637227f8ead0c3a06.
We can't remove the old dockerfile and make commands as jenkins still calls `run-ruby-client-integration-tests` on deploy of api/admin (and merge of ruby client). 
The old dockerfile has proxy settings that are needed on jenkins
> Revert "remove old jenkins dockerfile"

- DOCUMENTATION.md
Not having a new line before the markdown table was causing the table
to not be rendered properly when this page gets displayed by our tech
docs.
> Fix formatting for the tech docs

- CHANGELOG.md
- lib/notifications/client/request_error.rb
- lib/notifications/client/version.rb
- spec/notifications/client/request_errors_spec.rb
Exceptions in Ruby return the exception message when calling `#to_s` on it:
```
> irb
irb(main):001:0> StandardError.new("Hi").to_s
=> "Hi"
```
Because this is default behaviour, libraries sometimes depend on `to_s` to get a readable version of the exception message. For example, the Sentry client does it to give the exception a name:
https://github.com/getsentry/raven-ruby/blob/065cf973cb0ad3672d0d213e80b6e8a9a8e6f8cb/lib/raven/event.rb#L144
Currently, Sentry reports do not show the error message set when raising the exception - it only displays `Notifications::Client::BadRequestError`:
This is because we’re [only defining `RequestError#message`](https://github.com/alphagov/notifications-ruby-client/blob/446923820d5133960d74eba6950f6c01168a3ea7/lib/notifications/client/request_error.rb#L1 …
> Expose exception message via `#to_s`

- CHANGELOG.md
- DOCUMENTATION.md
- lib/notifications/client/helper_methods.rb
- lib/notifications/client/version.rb
- spec/notifications/client/helper_methods_spec.rb
karlify some of the content.
note: some of the error messages are staying the same (eg "Document didn't pass the virus scan") because we're not sure if people might be using those strings to try and handle errors automatically. They're controlled by the API so people won't be aware when it suddenly switches.
However, this PR does change the file size too big error, that should be okay as it's only going to change when they upgrade the client library itself
> rename document to file

- DOCUMENTATION.md
This PR changes the wording of 2 message status descriptions:
- mentioning the 72 hour period in the _Sending_ status makes it explicit that this a message that remains in this state for longer than a users expects is not 'stuck'
- not mentioning the 72 hour period in the _Phone not accepting messages right now_ status should reduce any confusion for users who see this status after <72 hours
This change was prompted by feedback from a user on x-gov Slack:
>We sent out a message last night and there were a few numbers that did not get it, on checking one, it gives the message: _"The provider could not deliver the message after trying for 72 hours. This can happen when the recipient’s phone is off..."_ Given it is not even 24 hours after the text was sent, any ideas why this report is …
> Update status descriptions to help users understand the 72 hour period (Ruby)

- DOCUMENTATION.md
So our docs match our recent change to the API
alphagov/notifications-api#2701
> Update error messages for api keys not found

- DOCUMENTATION.md
The existing documentation suggests that the client returns an error object, whereas it actually raises an exception.
> Make it clearer that the client raises exceptions

- Dockerfile
- Makefile
- docker/Dockerfile
- notifications-ruby-client.gemspec
- spec/factories/client_request_errors.rb
- spec/factories/notifications_client.rb
**Update Ruby version**
Ruby version 2.4 is no longer supported. Also upgraded some of the development dependencies and fixed some deprecated syntax in the tests as a result.
These changes shouldn't have any effect on users of the gem. Changing the version of Ruby only changes the version of Ruby we use to run the tests, it doesn't force users of the gem to have Ruby version 2.6 installed.
**Remove `govuk-lint` development dependency**
This dependency is deprecated, and also wasn't being used. We can upgrade to the replacement, `rubocop-govuk`, but there are a lot of changes that it suggests, so it's better to look at this separately.
> Update Ruby version to 2.6

- DOCUMENTATION.md
This PR updates the status description tables so that:
* there's a separate table for emails and text messages
* all text message statuses are grouped together
* the `permanent failure` text message status is consistent with the Notify status page
It also replaces the extra status table under 'Get the status of multiple messages' with links to the other status tables.
> Update status table

- CHANGELOG.md
- DOCUMENTATION.md
- lib/notifications/client/helper_methods.rb
- lib/notifications/client/version.rb
- spec/notifications/client/helper_methods_spec.rb
Fixes the equivalent bug as https://github.com/alphagov/notifications-python-client/pull/165
so that CSV files are downloaded as CSV files rather than txt files
> Add `is_csv` parameter to prepare_upload to fix csv doc download

- CHANGELOG.md
- DOCUMENTATION.md
- bin/test_client.rb
- lib/notifications/client/response_template.rb
- lib/notifications/client/version.rb
- notifications-ruby-client.gemspec
- spec/factories/template_response.rb
- spec/notifications/client/get_template_spec.rb
- spec/notifications/client/get_template_version_spec.rb
This adds a new `letter_contact_block` attribute to the
`Notifications::Client::Template` class. `letter_contact_block` can be
`nil` or the contact block of a letter template and will now be returned
as part of the response from the `get_template_by_id`, `get_template_version`
and `get_all_templates` methods.
> Add letter_contact_block to Notifications::Client::Template

- DOCUMENTATION.md
The client documentation talks about address lines 1-6 and postcode (including mandatory nature of address lines 1,2 and postcode). Now that we are supporting address lines 1-7 we need to update the documentation to reflect this.
There is a question about what we should say in the docs about the mapping that we do from postcode, or that it is sort of degraded, but needs a bit of a thought for that.
After we have done this story, services will see the new address personalisation that we require and understand that it won’t be a breaking change for them.
> Update address fields to include line 7

- DOCUMENTATION.md
Wrong dash meant the bullet points didn't show up properly
> Fix personalisation

- CONTRIBUTING.md
- Makefile
The '--rm' flag in the 'run_with_docker.sh' script means containers
should clean themselves up automatically. If we need a command to
clean up Docker containers more generally, we should document this
centrally, rather than in each repo.
> Remove broken task to clean up Docker containers

- .dockerignore
In response to [1].
Although this image is only used locally (and the one on CI is built
in a clean working directory), it's reasonable to add an extra layer
of protection to stop any secrets making their way into images.
[1]: https://github.com/alphagov/notifications-functional-tests/pull/382#pullrequestreview-702069161
> Avoid baking environment.sh secrets into images

- CHANGELOG.md
- DOCUMENTATION.md
- lib/notifications/client/helper_methods.rb
- lib/notifications/client/version.rb
- spec/notifications/client/helper_methods_spec.rb
Adds optional parameters `confirm_email_before_download` and `retention_period` to the `prepare_upload` helper, to access new security features when sending a file by email.
Bumps the client version to 5.4.0
> Add support for send a file security features

- DOCUMENTATION.md
Two errors were missing the error type column, so the table wasn't displaying as it should:
> Add missing columns to "Send a file by email" error table

- CHANGELOG.md
- DOCUMENTATION.md
- lib/notifications/client/helper_methods.rb
- lib/notifications/client/version.rb
- notifications-ruby-client.gemspec
- spec/notifications/client/helper_methods_spec.rb
Update client for the new document download feature which allows
specifying a download filename for files sent by email.
This supercedes the old `is_csv` parameter that was inconsistent at best.
Given this, we are dropping support for `is_csv` altogether.
> Allow setting custom filenames for documents

- bin/test_client.rb
- this is adding further test cases for the additional fields returned from get_notification(id)
- in a previous PR, we added some unit tests but integration tests were missed
- https://github.com/alphagov/notifications-ruby-client/pull/143
[3. Add GET notification cost data to API clients and API client docs](https://trello.com/c/5VZrBNpU/845-3-add-get-notification-cost-data-to-api-clients-and-api-client-docs)
> chore: add integration tests for cost_details fields returned from get_notification(id)

- Dockerfile
- bin/test_client.rb
[Trello card](https://trello.com/c/D1m5uleD/952-run-api-client-integration-tests-as-part-of-new-pipeline)
Some small updates to make the integration tests runnable in the dev environments via the new deploy pipeline.
Also updates the integration tests to print a stack trace when they fail, to make debugging easier.
[Tested in dev-a](https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/162) (5 times in a row to check for flakiness)
> Make the integration tests compatible with the dev environments

- bin/test_client.rb
This removes `completed_at` from the list of fields that will always be `nil` for precompiled letters - whether or not this field is populated depends on the status of the notification.
> Adjust integration test for precompiled letters

- CHANGELOG.md
- lib/notifications/client/version.rb
- notifications-ruby-client.gemspec
The major version level of the `jwt` gem is now 3 and upgrading is prevented by the dependency limit in `notification-ruby-client`.
I have changed the gem dependencies:
* To allow version 3 of `jwt`
* To remove the restriction on the version of `bundler`
* To allow `factory_bot` to be upgraded with Ruby version 3+
> Allow the `jwt` gem to be upgraded
